- id: '1610593146218'
  alias: BaumAssistant - Set Fan Speed for Argon40
  description: Set fan speed of Argon40 for Raspberry Pi based on numeric value from
    slider
  trigger:
  - platform: state
    entity_id: input_number.argon40_fanspeed
  condition: []
  action:
  - service: argon40.set_fan_speed
    data:
      speed: '{{ states(''input_number.argon40_fanspeed'') }}'
  mode: single
- id: '1612529119404'
  alias: Notify about phone state
  trigger:
  - platform: state
    entity_id: sensor.fritz_box_6591_cable_kdg_call_monitor_fritzbox_callmonitor
  action:
  - service: notify.persistent_notification
    data:
      title: Phone
      message: "{% if is_state(\"sensor.fritz_box_6591_cable_kdg_call_monitor_fritzbox_callmonitor\"\
        , \"idle\") %}\n  Phone is idle\n{% elif is_state(\"sensor.phfritz_box_6591_cable_kdg_call_monitor_fritzbox_callmonitorone\"\
        , \"dialing\") %}\n  Calling {{ state_attr('sensor.fritz_box_6591_cable_kdg_call_monitor_fritzbox_callmonitor',\
        \ 'to_name') }} ({{ state_attr('sensor.phone', 'to') }})\n{% elif is_state(\"\
        sensor.fritz_box_6591_cable_kdg_call_monitor_fritzbox_callmonitor\", \"ringing\"\
        ) %}\n  Incoming call from {{ state_attr('sensor.fritz_box_6591_cable_kdg_call_monitor_fritzbox_callmonitor',\
        \ 'from_name') }} ({{ state_attr('sensor.phone', 'from') }})\n{% else %}\n\
        \  Talking to {{ state_attr('sensor.fritz_box_6591_cable_kdg_call_monitor_fritzbox_callmonitor',\
        \ 'with_name') }} ({{ state_attr('sensor.phone', 'with') }})\n{% endif %}"
  mode: single
- id: '1613513334468'
  alias: Shopping - Zeige Einkaufsliste
  description: ''
  trigger: []
  condition: []
  action:
  - service: notify.mobile_app_sm_g955f
    data:
      title: Denk an die Einkäufe
      message: Gelange hier zur Einkaufsliste
      data:
        clickAction: /shopping-list
        url: /shopping-list
  mode: single
- id: '1615934558420'
  alias: FRITZ!Box 6591 - Guest WiFi angeschaltet - Push Login details
  description: ''
  trigger:
  - platform: state
    entity_id: switch.fritzbox_6591_cable_kdg_guest_wifi
    to: 'on'
  condition: []
  action:
  - service: notify.persistent_notification
    data:
      title: BaumHaus-Guest WiFi eingeschaltet
      message: 'WLAN-SSID: BaumHaus-Guest <br> Password: test1234'
  mode: single
- id: '1616796514306'
  alias: SRHH - Push für die morgige Abholung
  description: Benachrichtige über morgige Müllabfuhr
  trigger:
  - platform: state
    entity_id: binary_sensor.srhh_blaue_papiertonne_1d
    to: '''on'''
  condition: []
  action:
  - service: notify.mobile_app_sm_g955f
    data:
      title: Müllabfuhr
      message: Die blaue Tonne rausstellen - morgen ist Abholung
      data:
        group: Müllabfuhr
        tag: blaue-Tonne
        sticky: 'true'
        actions:
        - action: HEATING_ON
          title: Test1
        - action: HEATING_OFF
          title: Später erinnern
  - service: notify.mobile_app_philipp_iphone8
    data:
      title: Müllabfuhr
      message: Die blaue Tonne rausstellen - morgen ist Abholung
      data:
        push:
          thread-id: Müllabfuhr
          category: mullabfuhr
        apns_headers:
          apns-collapse-id: blaue-Tonne
  mode: single
- id: '1619304793653'
  alias: Netatmo - Alarm in der Nacht
  description: ''
  trigger:
  - platform: event
    event_type: netatmo_event
    event_data:
      data:
        event_type: human
  condition:
  - condition: time
    after: 00:00
    before: 07:00
  action:
  - service: notify.persistent_notification
    data:
      message: Your message goes here
      title: 'Achtung: Person auf Grundstück'
  - service: light.turn_on
    target:
      entity_id:
      - light.ambiance_eingang_vorne
      - light.esszimmer_esstisch
      - light.kuche_deckenlicht
    data:
      brightness: 255
      flash: short
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - service: light.turn_off
    target:
      entity_id:
      - light.ambiance_eingang_vorne
      - light.esszimmer_esstisch
      - light.kuche_deckenlicht
    data:
      transition: 5
  mode: single
